name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["type: bug", "status: triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior
      placeholder: |
        1. Run `claude-rs` with `--flag`
        2. Type "..."
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened (include error messages, screenshots)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `claude-rs --version`
      placeholder: "claude-rs 0.2.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux (x86_64)
        - Linux (aarch64)
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Windows (x86_64)
        - Windows (ARM64)
        - Other
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust Version
      description: Output of `rustc --version`
      placeholder: "rustc 1.86.0 (a1b2c3d4 2025-03-01)"

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Paste any relevant log output (run with `RUST_LOG=debug`)
      render: shell

  - type: textarea
    id: implementation-notes
    attributes:
      label: Implementation Notes (optional)
      description: Maintainer notes, suspected root cause, or technical pointers
      placeholder: |
        - Suspected module/path:
        - Possible root cause:
        - Constraints:

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
