name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["type: enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please describe your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is it related to a frustration?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered

  - type: textarea
    id: implementation-notes
    attributes:
      label: Implementation Notes (optional)
      description: Maintainer notes, technical direction, constraints, or rollout plan

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies / Blockers (optional)
      description: Related issues, upstream blockers, or required sequencing
      placeholder: |
        - Blocked by #...
        - Depends on #...
        - Must ship after #...

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the application does this affect?
      options:
        - TUI / Interface
        - ACP Protocol / Connection
        - Terminal Operations
        - Permission System
        - CLI Arguments
        - Configuration
        - Performance
        - Documentation
        - Other

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and discussions to ensure this is not a duplicate
          required: true
